name: Mirror to gitee Repo

on: [ push ]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITHUBGITEE }}
        with:
          source-repo: "git@github.com:ycvcb123/githubgitee.git"
          destination-repo: "https://gitee.com/yezw/githubgitee.git"
